#INITIAL SETTINGS
data_directory: ./data/
train_data_name: train.csv
test_data_name: test.csv
seed: 42
competition_name: titanic
path_to_save_data: ./data
test_size: 0.3
n_jobs: -1
artifact_path: ./artifacts/
model_name: model.joblib